version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protekspec-frontend
    restart: unless-stopped
    ports:
      - "3010:4173"
    env_file:
      - .env 